defaults: &defaults
  app_version: "0.0.1"
  per_page: 20
  default_from: "development@ryohi.sakura.ne.jp"
  #  url: "http://ryohi.com"
  url: "http://localhost:3030"
  basic_name: <%= ENV['ADMIN_USER'] %>
  basic_pass: <%= ENV['ADMIN_PASS']%>
  prefectures:
    - 北海道
    - 青森県
    - 岩手県
    - 宮城県
    - 秋田県
    - 山形県
    - 福島県
    - 茨城県
    - 栃木県
    - 群馬県
    - 埼玉県
    - 千葉県
    - 東京都
    - 神奈川県
    - 新潟県
    - 富山県
    - 石川県
    - 福井県
    - 山梨県
    - 長野県
    - 岐阜県
    - 静岡県
    - 愛知県
    - 三重県
    - 滋賀県
    - 京都府
    - 大阪府
    - 兵庫県
    - 奈良県
    - 和歌山県
    - 鳥取県
    - 島根県
    - 岡山県
    - 広島県
    - 山口県
    - 徳島県
    - 香川県
    - 愛媛県
    - 高知県
    - 福岡県
    - 佐賀県
    - 長崎県
    - 熊本県
    - 大分県
    - 宮崎県
    - 鹿児島県
    - 沖縄県
  signature: |
    --
    旅費com https://ryohi.com/ 旅費精算書作成システム
    株式会社ラビックス
  release_notes:
    - version: '2.0'
      date: 2017-07-11
      description: "社員に依存していた日当と宿泊費のパターンを、会社に依存するように変更し、日当と宿泊費を複数パターン選べる仕様にしました。その結果、近くの出張と遠くの出張を切り分けたりすることができるようになりました。"
    - version: '1.0'
      date: 2017-06-18
      description: "トップページの文章を変更し、正式リリースしました。"
    - version: '0.8'
      date: 2017-06-17
      description: "交通費の金額の入力フォームに、入力された金額を2倍にするボタンと半分にするボタンをつけました。これにより、往復と片道の計算がしやすくなりました。"
    - version: '0.7'
      date: 2017-02-01
      description: "出張の詳細と月別集計表に印刷ボタンをつけました。"
    - version: '0.6'
      date: 2016-04-01
      description: "月別集計表を表示できるようにしました。"
    - version: '0.5'
      date: 2016-02-19
      description: "出張を月単位ではなく、1回毎の出張単位で管理するように変更しました。"
    - version: '0.4'
      date: 2016-01-28
      description: "リリースノートを表示するようにしました。"
    - version: '0.3'
      date: 2016-01-22
      description: "日当や宿泊費をオフにして、交通費だけを精算できるオプションを追加しました。"
    - version: '0.2'
      date: 2015-12-15
      description: "出張ごとにかかった出張費をまとめて表示するように修正しました。"
    - version: '0.1'
      date: 2015-12-07
      description: "ベータ版をリリースしました。"

development:
  <<: *defaults
  subject: '【Dev】'

test:
  <<: *defaults
  subject: '【Pre】'

production:
  <<: *defaults
  subject: 
  default_from: "support@ryohi.com"
  url: "https://www.ryohi.com"

